### ISSUE TITLE
Unused new exports from dependency marked as "changes"

### ISSUE THREAD

**Issue by mheavenor** [haroldadmin/functions-differ#4]
Consider the following two files where `foo.ts` is the root of an exported Firebase Function

```
//importMe.ts
export const foo = 5;

//foo.ts
import { foo } from "./importMe";
...
```

If you add `export const bar = 10;` to `importMe.ts`, `foo.ts` will be marked as changed even though it's imports (the value of foo) did not change.

**Comment by haroldadmin** [comment]
This is a valid question, but unfortunately there's not much I can do to help you here.

`functions-differ` uses [esbuild](https://esbuild.github.io/) under the hood to bundle the function's code into a single file with tree shaking and minification, and then hashes those bundles to find changes. 

The cause of your issue seems to be tree shaking. It does not seem to be working as thoroughly as it should. Maybe raise this issue on [esbuild's repository](https://github.com/evanw/esbuild)?

**Comment by mheavenor** [comment]
Ah yes, that makes sense. I dont think that tree shaking can get rid of a module's exports.
